runmode: debug               # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: apigo                  # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apigo.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  engine: mysql
  url: root:R0otAwc10ud@tcp(172.16.2.100:8090)/ailab?charset=utf8
